### ISSUE TITLE
Use target="_blank" for external links

### ISSUE THREAD

**Issue by StanleyMasinde** [winniebosy/resume#1]
Eg for the line below it will be
https://github.com/winniebosy/resume/blob/b186ea83c559da69770eeeb0eb7ba80290f7242c/index.html#L164

```html
<a class="card-live-site " href="https://app.netlify.com/sites/landing-page-e-learning/overview" aria-label="e-learning live site" target="_blank"  rel="noopener noreferrer">Live Site</a>
```

`rel="noopener noreferrer"` will instruct the browser to open the link without giving the new destination the context of the current page.  It has no major effect here back it can cause security issues. 

Check the link below for more.
https://thecodest.co/blog/web-app-security-target-_blank-vulnerability/

**Comment by StanleyMasinde** [comment]
Also the correct link for the site above is https://landing-page-e-learning.netlify.app/

**Comment by winniebosy** [comment]
Thank you for pointing this out
